### ISSUE TITLE
can you explain the idea behind this

### ISSUE THREAD

**Issue by cocodrino** [yarf-framework/yarf#14]
Hi, I'm courious about this code

```go

type Hello struct {
    yarf.Resource
}

```

for me it's a bit verbos create this struct, compared to other frameworks inspired by ruby sinatra (similar to gorrilla routes) but I'm pretty sure than there is a great idea behind this, can you explain me why did you choose this implementation? thanks

**Comment by leonelquinteros** [comment]
Well, to start, the frameworks you mentioned are "generic" web frameworks, while YARF is designed to be a REST framework. Even when you can do any web development with it, the entire idea behind the design is to represent REST resources to match the philosophy of REST APIs https://en.wikipedia.org/wiki/Representational_state_transfer 

There is also an intention to create an Object Oriented design for the code that will consume the framework, other than just write random functions and attach them to a router. 

On a REST API, conceptually a URL will represent an entity of your system that will be able to handle the different actions (HTTP verbs) available for it. So when you create a (i.e.) `Product` resource for a `/products` URL you'll want to handle GET, POST, PUT and DELETE methods related to that. And as all these methods for that URL will work over the same entity, it makes sense to have them grouped (and isolated) inside the `Product` struct.

On other, more minimalistic, approaches makes sense to have these functions randomly created across the code, but i found that when the projects gets bigger and bigger you need some kind of organization and namespacing for your code, otherwise it becomes hard to maintain and extend. 
YARF proposes this design principle that i think can be useful and at the same time isn't too intrusive that you can't do things other way around. 

And to close, this design allowed me to provide several utilities (and to implement new ones on the future) that will help on the development without having to introduce too much overhead on the consumer code. I.e. Once you define and composite a yarf.Resource, you already have all HTTP verbs automatically handled for that URL and returning the corresponding HTTP error status for these that aren't implemented yet: `501 Not Implemented`

I think these are the main reasons to have this design. Isn't better or worst, is just more focused to a type of projects (REST APIs) and using Object Oriented Design principles. 

That said, I can be wrong on everything and contributions, improvements, bug reports, suggestions, discussions and questions like this one are totally welcome.
